name: Compile MQL5 Project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Compile using GitHub Action
      uses: ERM2000/mql5_compile_action@v1.1  # Corrected author name
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Experts/InverseFVG_Trend_Strategy.mq5
        include: include
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled_EA
        path: |
          MQL5/Experts/*.ex5
          MQL5/Experts/*.ex4