name: Compile MQL5 Project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4
      
    - name: Set up MetaTrader 5
      run: |
        # Download MT5 portable version
        $url = "https://download.mql5.com/cdn/web/2060/mt5setup.exe"
        $output = "$env:GITHUB_WORKSPACE\mt5setup.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        
        # Install MT5 silently
        Start-Process -FilePath $output -ArgumentList "/S" -Wait
        
        # Verify installation
        $mt5Path = "C:\Program Files\MetaTrader 5"
        if (-not (Test-Path "$mt5Path\metaeditor64.exe")) {
            Write-Error "MT5 installation failed"
            exit 1
        }
        
        # Set environment variables
        echo "MT5_PATH=$mt5Path" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "MQL5_PATH=$mt5Path\MQL5" | Out-File -FilePath $env:GITHUB_ENV -Append
        
    - name: Compile EA
      run: |
        $editorPath = "${{ env.MT5_PATH }}\metaeditor64.exe"
        $sourcePath = "${{ github.workspace }}\Experts\InverseFVG_Trend_Strategy.mq5"
        
        # Run compilation
        & "$editorPath" /compile:"$sourcePath" /log /inc:"${{ github.workspace }}\include"
        
        # Verify output
        $ex5Path = "${{ env.MQL5_PATH }}\Experts\InverseFVG_Trend_Strategy.ex5"
        if (-not (Test-Path $ex5Path)) {
            Write-Error "Compilation failed: $ex5Path not found"
            Get-Content "$env:TEMP\metaeditor.log"
            exit 1
        }
        Write-Host "Successfully compiled: $ex5Path"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: Compiled_EA
        path: ${{ env.MQL5_PATH }}\Experts\InverseFVG_Trend_Strategy.ex5